;;; -*- MODE: LISP; SYNTAX: ANSI-COMMON-LISP; PACKAGE: CL-USER; BASE: 10 -*-

(IN-PACKAGE :CL-USER)

;;;
;;; DEFINE PACKAGES
;;;

(DEFPACKAGE heap
  (:USE
   common-lisp)
  (:EXPORT 
   
   create-heap
   heap-count
   heap-empty-p
   heap-clear
   loop-over-heap-items
   heap-insert
   heap-items
   heap-find
   heap-remove
   heap-remove-item
   heap-find-item
   heap-peek))


(DEFPACKAGE TOOLS
    (:USE
     #+:clim CLIM
     #+:clim CLIM-LISP
     #-:clim common-lisp)
  (:EXPORT 

					;NNF
   MAXIMUM 
   MINIMUM

   SMALLEST
   GREATES
   
   BOOLEAN-DNF
   SIMPLIFY-BOOLEAN-EXPRESSION
   GET-BOOLEAN-DNF

   TRANSFORM-XY-LIST
   
   QBOX
   SHOW-SUBCLASSES
   SHOW-QBOX

   SUBCLASS-RESPONSIBILITY
   TO-BE-IMPLEMENTED
   
   TREE-REVERSE
   TREE-REMOVE
   TREE-FLATTEN
   TREE-COLLECT-IF
   TREE-FIND
   TREE-FIND-IF
   TREE-MAP
   TFLATTEN
   
   MEASURE-TIME

   MY-ROUND
   =>
   <=>
   
   KILL
   RUN

   BLANK-LINE-P

   WITH-STANDARD-OUTPUT-TO-FILE

   CONCEPT-NAME
   CHANGE-PACKAGE-OF-DESCRIPTION

   INTERVALL-INTERSECTS-P
   CIRCLE-INTERVALL-INTERSECTS-P
   LIES-IN-CIRCLE-INTERVALL-P	  
   CIRCLE-INTERVALL-LENGTH
   
   RAD-TO-DEG
   DEG-TO-RAD
   
   +2PI+
   +PI/2+
   
   RECODE-GERMAN-CHARACTERS
   
   ZEROP-EPS
   =-EPS
   <=-EPS
   >=-EPS

   ONE-OF
   
   XOR
   
   DEFUN-MEMO
   DEFMETHOD-MEMO
   RESET-MEMO
   
   YES
   NO

   ENSURE-LIST	  
   CIRCLE-SUBSEQ
   MYNCONC
   MY-FORMAT
   PUSHEND
   MAKE-CYCLIC
   
   GET-LAMBDA-ARGS
   
   SET-EQUAL
   SET-DISJOINT	  

   FAC
   N-OVER-K
   K-OUT-OF-N
   COMPUTE-ALL-SUBSETS
   COMPUTE-ALL-SUBSETS-OF-CARDINALITY
   LOOP-OVER-SUBSETS-OF-CARDINALITY
   POWER
   PROD
   NEWPROD
   PERM
   PERMUTATIONS
   IS-PERMUTATION-P 

   FORCECDR
   
   STRINGSUBST-CHAR-WITH-STRING
   STRING-SUBSTITUTE
   
   BUILD-ELEM-PAIRS-IN-LIST
   VECTOR-ORIENTATION
   SPLICE-IN
   
   REORDER
   
   LOOP-OVER-AVL-TREE
   INSERT-INTO-AVL-TREE
   DELETE-FROM-AVL-TREE
   AVL-TREE-EQUAL
   FIND-IN-AVL-TREE 
   MAKE-AVL-TREE-FROM-LIST
   PRINT-AVL-TREE))

(DEFPACKAGE DAG
    (:USE
     TOOLS
     #+:clim CLIM
     #+:clim CLIM-LISP
     #-:clim common-lisp)
  #+:clim 
  (:SHADOWING-IMPORT-FROM CLIM-LISP
			  BOOLEAN) 
  (:EXPORT 
   
   DAG
   DAG-NAME
   MAKE-DAG
   MAKE-DAG-NODE

   COPY-DAG-NODE

   COM-MAKE-SUBDAG-FROM-NODE
   COM-EXCHANGE-CHILD-NODE-POSITIONS
   
   DAG-BROWSER
   DAG-OPTIONS
   DAG-INFO
   DAG-DISPLAY

   DRAW-DAG-NODE
   DRAW-DAG-DISPLAY
   SHOW-TOP-P
   SHOW-BOTTOM-P
   ACCEPT-OPTIONS
   
   DAG-NODE
   DAG-NODES
   
   DAG-ROOTS
   DAG-LEAVES

   DAG-TOP
   DAG-BOTTOM

   ORIENTATION
   
   
   DAG-ROOT
   FIND-DAG-NODE   
   
   DAG-NODE-NAME
   DAG-NODE-MARKED-P
   DAG-NODE-PARENTS
   DAG-NODE-CHILDREN
   DAG-NODE-ANCESTORS
   DAG-NODE-DESCENDANTS
   IN-DAG

   MARK-DAG-NODE
   FN-MARK-DAG-NODE
   UNMARK-DAG-NODE
   MARK-ALL-DAG-NODES
   FN-MARK-ALL-DAG-NODES
   UNMARK-ALL-DAG-NODES
   
   DAG-ISOMORPHIC-P
   NODE-EQUIVALENT-P
   INSERT-DAG-NODE
   DELETE-DAG-NODE
   
   VISUALIZE-DAG   

   MAKE-POSTSCRIPT-FILE
   CREATE-CLOS-CLASSES   
   COMPUTE-TRANSITIVE-CLOSURE
   COMPUTE-HASSE-DIAGRAM))


(DEFPACKAGE GUI-TOOLS
    (:USE 
     #+:clim CLIM
     #+:clim CLIM-LISP
     #-:clim common-lisp
     TOOLS)
  (:EXPORT
   WITH-CORRECT-CLIPPING
   DRAW-VECTOR-TEXT
   FILE-SELECTOR
   MCL-PANE
   INVERSE-HIGHLIGHTER
   WITH-CENTERING
   WITH-BORDER
   DRAW-MARKER*
   GET-SIZE-OF-GRAPHIC))


(DEFPACKAGE PERSISTENCE-MANAGER
    (:USE
     COMMON-LISP)
  (:SHADOW #:DEFCLASS #:DEFSTRUCT)
  (:EXPORT 
   #:DEFPERSISTENTCLASS 
   #:DEFPERSISTENTSTRUCT 
   #:INITIALIZE-LOADED-PERSISTENT-OBJECT
   #:MAKE-OBJECT-PERSISTENT
   #:LOAD-PERSISTENT-OBJECT
   #:PRINT-PERSISTENCE-MANAGER-INFO

   #:USER-WRITE-CONSTRUCTOR
   #:USER-WRITE-COMPONENT-CONSTRUCTOR
   #:USER-WRITE-INITIALIZER
   #:USER-WRITE-COMPONENT-INITIALIZER
   #:USER-FILL-OBJECT 
   #:USER-READ-COMPONENT-OBJECT
   #:USER-CREATE-EMPTY-OBJECT))


(DEFPACKAGE RACER-DAG
    (:USE
     DAG
     RACER
					;TOOLS
     #+:clim CLIM-LISP
     #+:dlamps CLIM
     #-:clim common-lisp)  
  #+:clim 
  (:SHADOWING-IMPORT-FROM CLIM-LISP
			  BOOLEAN) 
  (:EXPORT 
   GET-RACER-TAXONOMY))


(DEFPACKAGE GEOMETRY 
    (:USE
     COMMON-LISP
     TOOLS 
     PERSISTENCE-MANAGER)
  (:EXPORT 
   
   +RCC1-RELATIONSHIPS+   
   +RCC2-RELATIONSHIPS+
   +RCC3-RELATIONSHIPS+   
   +RCC5-RELATIONSHIPS+
   +RCC8-RELATIONSHIPS+
   
   INFINIT

   COARSER
   FINER
   
   GEOM-THING
   GEOM-POINT
   GEOM-LINE
   GEOM-CHAIN-OR-POLYGON
   GEOM-CHAIN	   
   GEOM-POLYGON
   GEOM-AGGREGATE
   BOUNDING-BOX
   BOUNDING-BOX-MIXIN
   
   DELETE-OBJECT
   
   POLYGON
   CHAIN

   MAKE-CIRCLE
   MAKE-ARC

   MAKE-POINT
   P
   MAKE-LINE
   L
   MAKE-POLYGON
   POLY
   MAKE-CHAIN
   CHAIN
   MAKE-AGGREGATE
   AGG
   MAKE-BOUNDING-BOX
   BB

   BOUNDING-BOX-P
   
   BOUND-TO
   
					;ID
   MARK-VALUE
   MARK-OBJECT
   X
   Y
   DET
   DET-0-VECS
   BB-WIDTH
   BB-HEIGHT
   
   P1 
   P2
   CENTROID
   
   P1-OF
   P2-OF
   CENTROID-OF
   PCENTER-OF
   

   PMIN
   PMAX
   PCENTER
   RADIUS
   
   SEGMENTS	  
   POINT-LIST
   HAS-PARTS
   PART-OF
   
   POINT-=-P
   POINT->=-P
   POINT-<=-P
   LINE-=-P
   
   JOINS-P
   PARALLEL-P
   UPRIGHT-P
   
   PRIMARY-P
   COMPONENT-P 
   DIRECT-COMPONENT-P 
   COMMON-ROOT-P
   GET-ALL-MASTERS
   GET-ALL-COMPONENTS 
   GET-DIRECT-COMPONENTS
   GET-ALREADY-PRESENT-DIRECT-MASTER
   GET-TOPMOST-MASTER
   GET-TOPMOST-COMMON-MASTER
   GET-DIRECT-COMMON-MASTER
   GET-DIRECT-COMMON-MASTER-FROM-LIST
   
   
   FOR-EACH-MASTER-HOLDS-P
   FOR-EACH-COMPONENT-HOLDS-P
   
   FOR-SOME-MASTER-HOLDS-P
   FOR-SOME-COMPONENT-HOLDS-P

   CALCULATE-BOUNDING-BOX
   INVALIDATE-BOUNDING-BOX

   CALCULATE-AREA
   DISTANCE-BETWEEN
   
   CALCULATE-BOUNDING-BOX-FOR-COMPLEX-OBJECT
   CALCULATE-CENTROID
   
   CALCULATE-INTERSECTION-POINT
   CALCULATE-INTERSECTION-LINE
   
   ANGLE-DIFFERENCE
   
   DISTANCE-BETWEEN*
   DISTANCE-BETWEEN-POINT-AND-LINE
   DISTANCE-BETWEEN
   DISTANCE-BETWEEN-XY

   LENGTH-OF-LINE 
   
   POINT-TRULY-INSIDE-BOX-P
   POINT-TRULY-INSIDE-BOX-P*

   POINT-INSIDE-BOX-P
   POINT-INSIDE-BOX-P*
   
   POINT-TRULY-OUTSIDE-BOX-P
   POINT-TRULY-OUTSIDE-BOX-P*

   POINT-OUTSIDE-BOX-P
   POINT-OUTSIDE-BOX-P*
   
   BOX-OVERLAPS-BOX-P
   BOX-OVERLAPS-BOX-P*
   
   ENLARGED-BOX-OVERLAPS-BOX-P
   
   BOX-TRULY-OVERLAPS-BOX-P
   BOX-TRULY-OVERLAPS-BOX-P*
   
   BOX-TOUCHES-BOX-P
   BOX-TOUCHES-BOX-P*

   BOX-INSIDE-BOX-P
   BOX-INSIDE-BOX-P*
   
   BOX-TRULY-INSIDE-BOX-P
   BOX-TRULY-INSIDE-BOX-P*
   
   LINE-INTERSECTS-BOX-BORDER-P
   LINE-INTERSECTS-BOX-BORDER-P*
   
   NORMALIZE
   ANGLE-BETWEEN
   ANGLE-BETWEEN*		   
   DISTANCE-AND-ORIENTATION
   DISTANCE-AND-ORIENTATION*
   GLOBAL-ORIENTATION
   
   
   MAKE-MATRIX
   RESET
   TRANSLATE
   SCALE
   ROTATE
   COMPOSE
   WITH-MATRIX	   
   WITH-TRANSLATION
   WITH-SCALING
   WITH-ROTATION
   WITH-NO-MATRIX-AT-ALL
   
   PROPORTIONAL-2-POINT
   FIXED-SY-2-POINT	   

   LIES-ON-P
   LIES-ON-P*	   
   INSIDE-P  
   INSIDE-P*
   OUTSIDE-P
   OUTSIDE-P*
   INTERSECTS-P
   CROSSES-P
   CROSSES-P*
   CROSSED-BY-P   
   TOUCHES-P
   COVERS-P
   COVERED-BY-P
   OVERLAPS-P
   CONGRUENT-P
   0D-TOUCHES-P
   1D-TOUCHES-P
   1D-INTERSECTS-P
   EQUAL-P
   INSIDE-EPSILON-P
   INSIDE-EPSILON-P*

   CALCULATE-RELATION
   INVERSE
   CONTAINS-P

   GET-EPSILON-ENCLOSURE-RELEVANT-POINTS
   GET-EPSILON-ENCLOSURE-RELEVANT-POINTS*

   SEGMENT-LIST-OK-P
   
   BORDERS
   BORDERED-BY
   DISJOINT
   LIES-ON
   CROSSES   
   CROSSED-BY
   TOUCHES
   0D-INTERSECTS	       
   1D-INTERSECTS		
   INTERSECTS
   INSIDE
   CONTAINS
   COVERS
   COVERED-BY
   OVERLAPS
   CONGRUENT

   CALCULATE-RELATION
   CALCULATE-RCC-RELATION
   INVERSE-RCC-RELATION
   NEGATED-RCC-RELATION


   ORIENTATION
   DECODE-CCW
   ORIENTATE-COUNTERCLOCKWISE
   ORIENTATE-CLOCKWISE
   AFFECTED-BY-MATRIX-P
   INSERT-NEW-BORDER-POINTS   
   ))

(DEFPACKAGE SQD 
    (:USE
     COMMON-LISP
     TOOLS
     PERSISTENCE-MANAGER)
  (:EXPORT
   READ-SQD-FILE
   SET-CLIENT-BB
   CONSTRUCT-OBJECT-FOR
   LOOKUP-OS
   *OS*))


(DEFPACKAGE GRAPH
    (:USE 
     TOOLS
     #+:clim CLIM
     #+:clim CLIM-LISP
     #-:clim common-lisp
     PERSISTENCE-MANAGER
     GUI-TOOLS)
  #+:clim 
  (:SHADOW
   CLIM:COLOR)
  (:EXPORT 
   VISUALIZE
   
   GRAPH
   GRAPH-ITEM
   EDGE
   NODE
   NAME

   MAKE-GRAPH
   DELETE-GRAPH

   MAKE-NODE
   DELETE-NODE

   MAKE-EDGE
   DELETE-EDGE
   
   FIND-GRAPH
   FIND-NODE
   FIND-EDGE

   GET-NODES
   GET-EDGES
   GET-EDGES-BETWEEN

   NO-OF-NODES
   NO-OF-EDGES

   COPY-GRAPH
   COPY-NODE
   COPY-EDGE
   COPY-GRAPH-ITEM
   
   IN-GRAPH
   
   INFO
   KIND 
   COLOR
   RESET-KINDS
   
   MARKED-P
   MARK
   UNMARK

   WITH-MARKED-OBJECTS
   WITH-NEW-MARKING-CONTEXT 

   NODE-COUNTER
   EDGE-COUNTER

   GET-NODE-POSITION

   FROM 
   TO
   ID))


(DEFPACKAGE THEMATIC-SUBSTRATE
    (:nicknames ts)
  (:USE 
   #+:clim CLIM 
   #+:clim CLIM-LISP
   #-:clim common-lisp
   TOOLS 
   RACER
   PERSISTENCE-MANAGER
   GRAPH
   DAG
   NRQL-SYMBOLS)

  (:SHADOWING-IMPORT-FROM TOOLS
			  NO) 

  #+:clim 
  (:SHADOWING-IMPORT-FROM CLIM-LISP
			  BOOLEAN)

  (:SHADOWING-IMPORT-FROM GRAPH
			  COLOR) 
  
  (:EXPORT 

   *RACER-WUNA-P*
   *CUR-SUBSTRATE*
   *ALL-SUBSTRATES*
   *NODE-DESCRIPTION-CLASS*
   *EDGE-DESCRIPTION-CLASS* 
   *NON-DETERMINISM-P* 

   *LAST-QUERY*
   *RUNNING-QUERY*
   *RUNNING-SUBSTRATE*

   ABORT-SEARCH-P

   NODE
   EDGE
   OBJECT
   SUBSTRATE
   SUBSTRATE-OBJECT
   SUBSTRATE-NODE
   SUBSTRATE-EDGE   
   CONCEPT 
   ROLE

   NODE-TABLE
   EDGE-TABLE

   REGISTER-BINDINGS 

   RACER-SUBSTRATE
   RACER-SUBSTRATE-NODE
   RACER-SUBSTRATE-EDGE
   NON-THEMATIC-NODE-P
   THEMATIC-NODE-P
   NON-THEMATIC-EDGE-P
   THEMATIC-EDGE-P
   ESTABLISH-CONTEXT-FOR
   SET-CONTEXT-FOR
   
   ABOX
   TBOX    
   RACER-PACKAGE

   CONVERT-TO-RACER-INDIVIDUAL-NAME
   CONVERT-TO-RACER-TBOX-NAME
   CONVERT-TO-RACER-ABOX-NAME
   CONVERT-TO-RACER-ROLE-EXPRESSION
   CONVERT-TO-RACER-CONCEPT-EXPRESSION
   CONVERT-TO-RACER-CONSTRAINT-EXPRESSION
   CONVERT-TO-RACER-ATTRIBUTE-EXPRESSION

   ALL-SUBSTRATES
   
   GET-STANDARD-NODE-CLASS
   GET-STANDARD-EDGE-CLASS
   GET-STANDARD-NODE-DESCRIPTION-CLASS
   GET-STANDARD-EDGE-DESCRIPTION-CLASS
   
   COPY
   COPY-SO
   CONSISTENT-P
   EQUIVALENT-P
   
   CREATE-SUBSTRATE
   DELETE-SUBSTRATE
   DELETE-ALL-SUBSTRATES
   GET-ALL-SUBSTRATES
   FIND-SUBSTRATE
   WITH-SUBSTRATE
   IN-SUBSTRATE
   WITH-SUBSTRATE*
   IN-SUBSTRATE*
   
   ID
   CREATE-NODE
   REGISTER-NODE
   REGISTER-EDGE
   ADD-TO-NODE
   ADD

   CHANGE-DESCRIPTION

   SAVE-CURRENT-DESCRIPTION
   LOAD-SAVED-DESCRIPTION
   POP-DESCRIPTION-STACK

   ;;NODES
   ;;EDGES

   LOOP-OVER-NODES
   LOOP-OVER-EDGES

   GET-NODES
   GET-EDGES
   GET-EDGES-BETWEEN
   GET-UNDERSPECIFIED-EDGES
   SIMPLIFY 
   SCRAMBLE
   ESTABLISH-CONTEXT-FOR
   SET-CONTEXT-FOR

   CREATE-EDGE
   INVERSE-EDGE
   REFLEXIVE-EDGE-P
   UNDERSPECIFIED-P   
   FIND-EDGE
   DELETE-EDGE   
   GET-EDGES-BETWEEN
   
   GET-ASSOCIATED-ABOX-INDIVIDUAL
   GET-ASSOCIATED-SUBSTRATE-NODE
   
   GET-MISSING-EDGES
   GET-UNDERSPECIFIED-EDGES
   SIMPLIFY
   SUBGRAPH-ISOMORPHIC-P
   ISOMORPHIC-P
   SCRAMBLE
   
   RACER-TBOX
   RACER-ABOX

   SUBSTRATE-TBOX
   SUBSTRATE-ABOX
   SUBSTRATE-RBOX
   SUBSTRATE-NAME
   
   FIND-RBOX

   THEMATIC-NODES
   THEMATIC-EDGES
   DESCRIPTION
   RACER-OBJECT
   RACER-DESCRIPTION
   SUCCESSORS
   PREDECESSORS
   OUTGOING
   INCOMING
   FROM 
   TO

   CHANGE-PACKAGE-OF-DESCRIPTION
   TRANSFORM-RACER-EXPRESSION
   CONVERT-TO-RACER-DESCRIPTION

   RACER-DESCRIPTIONS-SUBSTRATE
   RACER-DESCRIPTIONS-SUBSTRATE-OBJECT
   RACER-DESCRIPTIONS-SUBSTRATE-NODE
   RACER-DESCRIPTIONS-SUBSTRATE-EDGE

   ;; ROLEBOX-SUBSTRATE

   FULL-DISJUNCTIVE-ROLE
   AXIOM 
   RBOX
   INCONSISTENT-P
   *CUR-RBOX*  
   ROLEBOX
   ROLEBOX-SUBSTRATE

   ROLEBOX-SUBSTRATE-NODE
   ROLEBOX-SUBSTRATE-EDGE   
   ROLEBOX-NODE-DESCRIPTION
   ROLEBOX-EDGE-DESCRIPTION

   +RCC1-ROLEBOX+
   +RCC2-ROLEBOX+
   +RCC3-ROLEBOX+
   +RCC5-ROLEBOX+
   +RCC8-ROLEBOX+

   RCC1-ROLEBOX
   RCC2-ROLEBOX   
   RCC3-ROLEBOX
   RCC5-ROLEBOX
   RCC8-ROLEBOX   

   +RCC1-ROLES+
   +RCC2-ROLES+
   +RCC3-ROLES+
   +RCC5-ROLES+
   +RCC8-ROLES+

   PO
   EC
   TPP
   TPPI
   EQ
   DC
   PP
   PPI
   NTPP
   NTPPI
   DR
   ONE
   O

   GET-ROLE
   INV-ROLE
   MAKE-INVERSE-DESCRIPTION
   INV 
   GET-DISJUNCTS
   AUX-DESCRIPTION
   SET-DESCRIPTION-TO-AUX-DESCRIPTION
   AUX-DESCRIPTION-CONSISTENT-P 
   APPLY-ROLEBOX-AXIOMS
   LOOKUP
   COMPUTE-MINIMAL-LABEL
   GET-IMPLIED-LABEL
   ENUMERATE-ATOMIC-CONFIGURATIONS
   HAS-NEXT-CONFIGURATION-P 
   GET-ALL-ATOMIC-CONFIGURATIONS
   FIRST-COMPLETION
   ALREADY-INCONSISTENT-P
   GET-SUPPORT
   ADD-MISSING-EDGES
   VISUALIZE
   IN-GRAPH 
   EDGE-SETT
   CONSISTENT-P
   EDGES
   WITH-RBOX
   IN-RBOX 

   ;; JEPD SUBSTRATE

   JEPD-ROLEBOX
   JEPD-SUBSTRATE   
   JEPD-SUBSTRATE-NODE
   JEPD-SUBSTRATE-EDGE
   JEPD-SUBSTRATE-NODE-DESCRIPTION
   JEPD-EDGE-DESCRIPTION-DESCRIPTION
   
   ;; DESCRIPTIONS

   SEMANTIC-ENTITY
   CHANGE-TEXTUAL-DESCRIPTION
   GET-TEXTUAL-DESCRIPTION


   RACER-CONCEPT-MIXIN
   RACER-ROLE-MIXIN
   INITIALIZE-DESCRIPTION
   CONCEPT-IMPLIES-P
   ROLE-IMPLIES-P

   NORMALIZE-RACER-ROLE
   NORMALIZE-RACER-CONCEPT
   IS-VALID-RACER-ROLE-EXPRESSION-P
   IS-VALID-RACER-CONCEPT-EXPRESSION-P
   IS-VALID-RACER-CONSTRAINT-EXPRESSION-P
   
   NEGATED-RACER-ROLE-P

   DESCRIPTION
   NODE-DESCRIPTION
   EDGE-DESCRIPTION

   GET-INVERSE-DESCRIPTION
   GET-NEGATED-DESCRIPTION

   GET-DISJUNCTS
   GET-CONJUNCTS
   
   CONCEPT-CONSISTENT-P
   ROLE-CONSISTENT-P
   CONCEPT-TAUTOLOGICAL-P
   ROLE-TAUTOLOGICAL-P   

   RESET-SAT-STATUS

   UNDERSPECIFIED-P
   IMPLIES-P
   CONSISTENT-P
   INCONSISTENT-P
   TAUTOLOGICAL-P
   EQUIVALENT-P
   

   INCONSISTENT
   SATISFIABLE 
   TAUTOLOGICAL

   RACER-ROLE
   RACER-CONCEPT
   
   SIMPLE-DESCRIPTION
   SIMPLE-NODE-DESCRIPTION
   SIMPLE-EDGE-DESCRIPTION
   RACER-DESCRIPTION
   RACER-NODE-DESCRIPTION
   RACER-EDGE-DESCRIPTION

   SIMPLE-CONJUNCTIVE-DESCRIPTION
   SIMPLE-DISJUNCTIVE-DESCRIPTION
   
   IS-ATOM-P 
   GET-NEGATED-ATOM

   MAKE-DESCRIPTION
   
   MAKE-NODE-DESCRIPTION
   MAKE-STANDARD-NODE-DESCRIPTION
   NCON
   MAKE-EDGE-DESCRIPTION
   MAKE-STANDARD-EDGE-DESCRIPTION 
   ECON

   MAKE-AND-DESCRIPTION
   MAKE-OR-DESCRIPTION
   
   TEXTUAL-DESCRIPTION 
   ORIGINAL-DESCRIPTION
   
   ;; QUERY

   QUERY
   
   RACER-ABOX-QUERY
   VIRTUAL-QUERY
   SUBSTRATE-QUERY
   COMPLEX-QUERY

   BOTTOM-QUERY
   TOP-QUERY
   REAL-BOTTOM-QUERY
   REAL-TOP-QUERY
   
   HYBRID-QUERY
   HOMOGENEOUS-QUERY

   OR-QUERY
   AND-QUERY

   HOMOGENEOUS-COMPLEX-QUERY

   ATOMIC-QUERY

   ATOMIC-VIRTUAL-QUERY

   COMPLEX-SUBSTRATE-QUERY

   ATOMIC-SUBSTRATE-QUERY

   HYBRID-OR-QUERY
   HYBRID-AND-QUERY

   COMPLEX-RACER-ABOX-QUERY

   PREDICATE-DESCRIPTION-QUERY

   RACER-DESCRIPTION-QUERY

   SIMPLE-DESCRIPTION-QUERY

   BINARY-QUERY
   UNARY-QUERY

   ATOMIC-RACER-ABOX-QUERY

   VIRTUAL-SIMPLE-QUERY
   VIRTUAL-EDGE-QUERY
   VIRTUAL-NODE-QUERY

   SUBSTRATE-RACER-QUERY
   SUBSTRATE-PREDICATE-QUERY
   SUBSTRATE-SIMPLE-QUERY

   COMPLEX-SUBSTRATE-OR-QUERY
   COMPLEX-SUBSTRATE-AND-QUERY

   SUBSTRATE-EDGE-QUERY
   SUBSTRATE-NODE-QUERY

   COMPLEX-RACER-ABOX-OR-QUERY
   COMPLEX-RACER-ABOX-AND-QUERY

   SIMPLE-DISJUNCTIVE-DESCRIPTION-QUERY
   SIMPLE-CONJUNCTIVE-DESCRIPTION-QUERY

   BIND-INDIVIDUAL
   EDGE-RETRIEVAL-QUERY
   INSTANCE-RETRIEVAL-QUERY

   VIRTUAL-SIMPLE-EDGE-QUERY
   VIRTUAL-SIMPLE-OR-EDGE-QUERY
   VIRTUAL-SIMPLE-AND-EDGE-QUERY
   VIRTUAL-SIMPLE-NODE-QUERY
   VIRTUAL-SIMPLE-OR-NODE-QUERY
   VIRTUAL-SIMPLE-AND-NODE-QUERY
   VIRTUAL-SIMPLE-OR-QUERY
   VIRTUAL-SIMPLE-AND-QUERY

   VIRTUAL-PREDICATE-EDGE-QUERY
   VIRTUAL-PREDICATE-NODE-QUERY

   SUBSTRATE-RACER-EDGE-QUERY
   SUBSTRATE-RACER-NODE-QUERY

   SUBSTRATE-PREDICATE-EDGE-QUERY
   SUBSTRATE-PREDICATE-NODE-QUERY

   SUBSTRATE-SIMPLE-EDGE-QUERY
   SUBSTRATE-SIMPLE-OR-EDGE-QUERY
   SUBSTRATE-SIMPLE-AND-EDGE-QUERY
   SUBSTRATE-SIMPLE-NODE-QUERY
   SUBSTRATE-SIMPLE-OR-NODE-QUERY
   SUBSTRATE-SIMPLE-AND-NODE-QUERY
   SUBSTRATE-SIMPLE-OR-QUERY
   SUBSTRATE-SIMPLE-AND-QUERY
   
   ERROR-PARSER-ASKS-WHAT-IS

   UNARY-QUERY-P
   BINARY-QUERY-P
   
   UNARY-SUBSTRATE-QUERY-P
   UNARY-ABOX-QUERY-P
   BINARY-SUBSTRATE-QUERY-P
   BINARY-ABOX-QUERY-P
   
   ATOMIC-QUERY-P
   ATOMIC-ABOX-QUERY-P
   ATOMIC-SUBSTRATE-QUERY-P

   OR-QUERY-P
   AND-QUERY-P
   COMPLEX-QUERY-P
   NOT-QUERY-P
   INV-QUERY-P
   BIND-INDIVIDUAL-QUERY-P

   AND-QUERY-AVAILABLE-P
   OR-QUERY-AVAILABLE-P

   MAKE-AND-QUERY
   MAKE-OR-QUERY
   
   PREDICATE

   GET-TEXTUAL-HEAD-ENTRY
   
   ;;; RUNTIME

   MATCHES-P
   RETRIEVE-MATCHING-OBJECTS
   RETRIEVE-CACHED-CONCEPT-INSTANCES
   RETRIEVE-CHACHED-INDIVIDUAL-FILLERS

   QUERYING-STARTED
   QUERYING-ENDED

   PREPARE-SUBSTRATE-FOR-QUERY-EXECUTION

   ANSWER-QUERY
   EXECUTE-QUERY 

   PREPARE-QUERY

   ;; REWRITING
   
   ADD-BINDINGS
   
   SYNTACTICALLY-REWRITE-QUERY
   SYNTACTICALLY-REWRITE-ATOMIC-QUERY

   SEMANTICALLY-REWRITE-QUERY
   SEMANTICALLY-REWRITE-ATOMIC-QUERY

   ;; PARSER
   
   GET-PARSER-CLASS-FOR-SUBSTRATE
   SUBQUERIES
   ALL-SUBQUERIES

   SKIP-P
   ACTIVE-P

   PARSER
   SIMPLE-PARSER
   RACER-PARSER
   RESERVED-TOKENS
   +RESERVED-TOKENS+

   PARSE-QUERY
   UNPARSE-QUERY

   GET-SUBEXPRESSIONS
   GET-EXPRESSION-TYPE
   MAKE-DISPATCHER
   
   VALID-NODE-AND-DESCRIPTION-P
   VALID-NODE-OR-DESCRIPTION-P
   
   VALID-EDGE-AND-DESCRIPTION-P
   VALID-EDGE-OR-DESCRIPTION-P
   
   VALID-CONCEPT-DESCRIPTION-P
   VALID-ROLE-DESCRIPTION-P

   SUBSTRATE-THING-P
   ABOX-THING-P
   VAR-P
   IND-P   


   ACTIVATE-ALL-SUBQUERIES
   DEACTIVATE-ALL-SUBQUERIES

   ACTIVATE
   DEACTIVATE

   VOI-FROM
   VOI-TO
   VOI  
   VOIS
   ALL-VOIS 
   REFERENCED-VOIS
   
   BOUND-TO
   CORRESPONDING-VOI-P
   TOP-LEVEL-QUERY
   
   SUBQUERY-OF
   SUBQUERIES

   QUERY-FN
   SOURCE

   BINDINGS-FOUND-P
   BINDINGS
   RESULT-BINDINGS
   COUNTER
   ANSWER-PATTERN

   ACTIVE-P
   SATISFIABLE-P
   SKIP-P
   NEGATED-P
   INVERSE-P

   TIMEOUT-P

   ;;; OPTIMIZER
   
   GET-SCORE
   OPTIMIZE-QUERY
   
   ;;; COMPILER

   COMPILE-QUERY
   COMPILE-SUBQUERY
   +CONTINUATION-MARKER+
   
   GET-TESTER-CODE
   GET-ENUMERATOR-CODE
   GET-FROM-ENUMERATOR-CODE
   GET-TO-ENUMERATOR-CODE

   GET-CODE-CHECK-IF-CACHE-MEMBER-P
   GET-CODE-RETURN-CACHE-MEMBERS

   DEFQUERY-CODE

   WITH-PROTECTED-BINDINGS
   GET-BINDING-CODE
   CACHE-BINDING-CODE

   GET-DNF-QUERY
   IN-DNF-P
   
   GET-CODE-RACER-RETRIEVE-RELATED-INDIVIDUALS
   GET-CODE-RACER-CHECK-INDIVIDUALS-RELATED-P 
   GET-CODE-RACER-RETRIEVE-INDIVIDUAL-FILLERS 

   ABORTABLE-DOLIST

   ;; QUERY REASONING

   SUBSTRATE-CONJUNCTS-CONSISTENT-P 
   ABOX-CONJUNCTS-CONSISTENT-P 
   
   QUERY-CONSISTENT-P
   QUERY-TAUTOLOGICAL-P
   QUERY-ENTAILS-P
   QUERY-ENTAILS-QUERY-P
   
   QUERY-SATISFIABLE
   QUERY-INCONSISTENT
   QUERY-TAUTOLOGICAL

   ))


(DEFPACKAGE PROVER
    (:USE 
     COMMON-LISP
     TOOLS
     DAG
     GRAPH
     HEAP
     PERSISTENCE-MANAGER
     THEMATIC-SUBSTRATE
     ;NRQL-SYMBOLS
     )
  (:SHADOW ABOX TBOX)
  (:EXPORT

   TBOX
   ABOX

   TBOX-CLASSIFIED-P
   ATOMIC-CONCEPT-ANCESTORS
   ATOMIC-CONCEPT-SYNONYMS
   CLASSIFY-TBOX
   ALL-CONCEPT-ASSERTIONS

   ROLEBOX-ABOX
   JEPD-ABOX
   LABEL
   ROLE
   ABOX-NODE
   ROLEBOX-ABOX-NODE
   JEPD-ABOX-NODE
   ABOX-EDGE
   ROLEBOX-ABOX-EDGE
   JEPD-ABOX-EDGE

   IN-ABOX
   IN-TBOX
   WITH-ABOX
   WITH-TBOX
   FIND-ABOX
   FIND-TBOX
   DELETE-ABOX
   DELETE-TBOX
   ABOX
   TBOX
   MAKE-ABOX
   MAKE-TBOX
   *CUR-ABOX*
   *CUR-TBOX*
   *ALL-TBOXES*
   *ALL-ABOXES*
   INSTANCE
   FORGET
   RELATED
   RELATE
   INS
   FGT
   REL
   SAT?
   ABOX-SAT?
   SUBSUMES?
   EQUIVALENT?
   EQUIVALENT-P
   SAT-P
   SUBSUMES-P
   ABOX-SAT-P
   MAKE-AXIOM
   DELETE-AXIOM
   DEF
   DEF*
   DEFINE-PRIMITIVE-CONCEPT
   DEFINE-CONCEPT
   DEFINE-PRIMITIVE-ROLE
   TAXONOMY
   RETRIEVE-CONCEPT-INSTANCES
   PREPARE 
   GET-CONCEPT-DEFINITIONS
   GET-PRIMITIVE-CONCEPT-DEFINITIONS
   GET-META-CONSTRAINTS
   GET-ORIGINAL-AXIOMS
   GET-NEW-AXIOMS
   GET-CONCEPT-NAMES
   GET-PRIMITIVE-CONCEPT-NAMES
   GET-NON-PRIMITIVE-CONCEPT-DEFINITIONS
   GET-NON-PRIMITIVE-CONCEPT-NAMES 
   GET-GCIS
   MAKE-AXIOM
   DELETE-AXIOM
   UNFOLD 
   COMPUTE-USED-BY-DAG
   DAG-ISOMORPHIC-P 
   CREATE-CLOS-CLASSES 
   MAKE-POSTSCRIPT-FILE 
   COMPUTE-HASSE-DIAGRAM))



(DEFPACKAGE SPATIAL-SUBSTRATE 
    (:USE 
     #+:clim CLIM
     #+:clim CLIM-LISP
     #-:clim common-lisp
     TOOLS 
     GUI-TOOLS
     PERSISTENCE-MANAGER   
     GEOMETRY	
     GRAPH
     THEMATIC-SUBSTRATE   
     PROVER
     NRQL-SYMBOLS
     SQD)
  (:SHADOWING-IMPORT-FROM GRAPH
			  COLOR)   
  (:SHADOWING-IMPORT-FROM THEMATIC-SUBSTRATE
			  TBOX ABOX)
  (:SHADOW ELEMENTS)

  #+:clim 
  (:SHADOWING-IMPORT-FROM CLIM
			  WITH-TRANSLATION
			  WITH-ROTATION
			  WITH-SCALING) 
  (:SHADOWING-IMPORT-FROM GEOMETRY 
			  BOUND-TO
			  POLYGON 
			  MAKE-POINT 
			  MAKE-LINE 
			  MAKE-POLYGON 
			  POLYGON 
			  MAKE-POINT 
			  MAKE-LINE 
			  MAKE-POLYGON)
  (:EXPORT 

   SHOW-NODES
   
   SPATIAL-INDEX
   
   SI-GEOM-THING
   SI-GEOM-POINT
   SI-GEOM-LINE
   SI-GEOM-CHAIN-OR-POLYGON
   SI-GEOM-CHAIN
   SI-GEOM-POLYGON

   INSTALL-AS-CURRENT-INDEX
   MAKE-SPATIAL-INDEX
   INIT-SPATIAL-INDEX
   RESET-SPATIAL-INDEX
   INSERT-INTO-SPATIAL-INDEX
   REMOVE-FROM-SPATIAL-INDEX

   ELEMENTS
   SET-VALUE-FOR
   GET-VALUE-FOR
   IN-BUCKET

   WITH-NEW-LEVEL
   WITH-SELECTED-BUCKETS
   WITH-SELECTED-OBJECTS
   
   BUCKET-SELECTED-P
   CANDIDATE-SELECTED-P

   GET-POINT-FROM-SPATIAL-INDEX*
   SORT-SPATIAL-INDEX
   
   XMIN
   YMIN 
   XMAX 
   YMAX

   DISTANCE
   AREA
   LENGTH
   MAP
   MAP-OBJECT
   
   BASIC-MAP-POINT
   BASIC-MAP-LINE
   BASIC-MAP-CHAIN
   BASIC-MAP-POLYGON
   
   MAP-OBJECT
   RACER-MAP-POINT
   RACER-MAP-LINE
   RACER-MAP-CHAIN
   RACER-MAP-POLYGON
   
   BASIC-MAP-EDGE
   RACER-MAP-EDGE
   
   SORT-CURRENT-SPATIAL-INDEX
   GET-CURRENT-MAP
   INSTALL-AS-CURRENT-MAP
   RESET-MAP
   LOAD-MAP
   STORE-MAP
   MAKE-MAP-FROM-SQD-FILE
   BOUND-TO
   
   OBJECTS
   ALL-OS
   READY
   MAP-VIEWER
   RESULT-INSPECTOR

   SET-CURRENT-MAP-POSITION-AND-RADIUS
   DRAW-CURRENT-MAP-TO-FOREIGN-STREAM

   HIGHLIGHT 
   UNHIGHLIGHT
   HIGHLIGHTED-P   
   
   FILE-SELECTOR
   MCL-PANE
   INVERSE-HIGHLIGHTER
   WITH-CENTERING
   WITH-BORDER
   DRAW-MARKER*
   GET-SIZE-OF-GRAPHIC))





(DEFPACKAGE DLMAPS 
    (:USE 
     COMMON-LISP
     TOOLS
     PERSISTENCE-MANAGER   
     GEOMETRY
     RACER
     ;; PROVER
     NRQL-SYMBOLS
     THEMATIC-SUBSTRATE
     SPATIAL-SUBSTRATE)
  (:SHADOWING-IMPORT-FROM GEOMETRY
			  DISJOINT
			  INVERSE
			  BOUND-TO)
  (:SHADOWING-IMPORT-FROM TOOLS
			  NO)
  (:SHADOWING-IMPORT-FROM THEMATIC-SUBSTRATE
			  ANSWER-QUERY)
  (:EXPORT
   *CURRENT-SUBSTRATE*
   CONVERT-MAP))


