(IN-TBOX OEJENDORF)

(DEFINE-PRIMITIVE-ROLE EC)

(DEFINE-PRIMITIVE-ROLE DC)

(DEFINE-PRIMITIVE-ROLE EQ)

(DEFINE-PRIMITIVE-ROLE PO)

(DEFINE-PRIMITIVE-ROLE TPP)

(DEFINE-PRIMITIVE-ROLE NTPP)

(DEFINE-PRIMITIVE-ROLE TPPI)

(DEFINE-PRIMITIVE-ROLE NTPPI)

;;;
;;;
;;;

(DEFINE-PRIMITIVE-ROLE DR)
(DEFINE-PRIMITIVE-ROLE PP)
(DEFINE-PRIMITIVE-ROLE PPI)

;;;
;;; Konvention: Konzepte, die mit -<TYP>* enden, 
;;; werden direkt anhand der OS-Tabelle zugesichert
;;; Damit z.B. Friedhof (Symbol) und Friedhof (Flaeche)
;;; unterschieden werden koennen, muss leider der Typ 
;;; -symbol* bzw. -flaeche* als Suffix angehaengt werden. 
;;; In die rechten Seiten der Konzeptaxiome werden teilweise 
;;; noch "nettere Namen" hinzugefuegt, einfach damit man 
;;; in den Queries nicht so viele und komplizierte Bezeichnungen 
;;; verwenden muss! Diese "Hilfskonzepte" = zusaetzliches Vokabular
;;; sind daran zu erkennen, dass "*" am Anfang steht!
;;; 


(DEFINE-PRIMITIVE-CONCEPT KARTEN-OBJEKT)

(DEFINE-PRIMITIVE-CONCEPT FLAECHE KARTEN-OBJEKT)

(DEFINE-PRIMITIVE-CONCEPT LINIE KARTEN-OBJEKT)

(DEFINE-PRIMITIVE-CONCEPT PUNKT KARTEN-OBJEKT)

(DEFINE-PRIMITIVE-CONCEPT SYMBOL KARTEN-OBJEKT)

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT GEO-OBJEKT KARTEN-OBJEKT) ; REPRAESENTIERT PHYSIKALISCHES OBJEKT

(DEFINE-PRIMITIVE-CONCEPT META-OBJEKT KARTEN-OBJEKT) ; REPRAESENTIERT *KEIN* PHYSIKALISCHE OBJEKT!

;;;
;;; Kartografische "Meta-Objekte"
;;;

(DEFINE-PRIMITIVE-CONCEPT KARTOGRAFISCHES-SYMBOL (AND META-OBJEKT SYMBOL))

(DEFINE-PRIMITIVE-CONCEPT KARTOGRAFISCHER-PUNKT (AND META-OBJEKT PUNKT))

(DEFINE-PRIMITIVE-CONCEPT KARTOGRAFISCHE-LINIE (AND META-OBJEKT LINIE))

;;;
;;; Grenzen und Konturen
;;;

(DEFINE-PRIMITIVE-CONCEPT KONTUR-LINIE (AND KARTOGRAFISCHE-LINIE LINIE))

(DEFINE-PRIMITIVE-CONCEPT ABGRENZUNGS-LINIE (AND KONTUR-LINIE))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT BLATTSCHNITT-BEARBEITUNGSGRENZE-FUER-SCHRIFT-LINIE* (AND KARTOGRAFISCHE-LINIE)) 

(DEFINE-PRIMITIVE-CONCEPT GITTERLINIE (AND KARTOGRAFISCHE-LINIE))

(DEFINE-PRIMITIVE-CONCEPT GK-GITTERLINIE-2-KM-LINIE* (AND GITTERLINIE))

(DEFINE-PRIMITIVE-CONCEPT GK-GITTERLINIE-1-KM-LINIE* (AND GITTERLINIE))

(DEFINE-PRIMITIVE-CONCEPT BAB-MITTELLINIE-LINIE* (AND KARTOGRAFISCHE-LINIE))

(DEFINE-PRIMITIVE-CONCEPT ZUSAETZLICHE-TOPOGRAPHIE-KEINE-NUTZUNGSGRENZE-LINIE* (AND KARTOGRAFISCHE-LINIE))

(DEFINE-PRIMITIVE-CONCEPT GITTERPUNKTE-FUER-DAS-EINPASSEN-VON-VORLAGEN-PUNKT* (AND KARTOGRAFISCHER-PUNKT))

;;;
;;; Grenzen / Konturen
;;;

(DEFINE-PRIMITIVE-CONCEPT TOPOGRAPHISCHE-GRENZE-LINIE* (AND ABGRENZUNGS-LINIE))

(DEFINE-PRIMITIVE-CONCEPT SPORTPLATZBEGRENZUNG-LINIE* (AND ABGRENZUNGS-LINIE))

(DEFINE-PRIMITIVE-CONCEPT NATURSCHUTZGEBIETSGRENZE-LINIE* (AND ABGRENZUNGS-LINIE))

(DEFINE-PRIMITIVE-CONCEPT ABRENZUNG-DER-BAB-USW-GEG-AUSFAHRT-UNSICHTBAR-LINIE* (AND ABGRENZUNGS-LINIE))

(DEFINE-PRIMITIVE-CONCEPT NUTZUNGSARTENGRENZE-LINIE* (AND ABGRENZUNGS-LINIE))

(DEFINE-PRIMITIVE-CONCEPT NUTZUNGSARTENGRENZE-UNSICHTBAR-LINIE* (AND NUTZUNGSARTENGRENZE-LINIE*))

(DEFINE-PRIMITIVE-CONCEPT BAB-RANDBEGRENZUNG-LINIE* (AND ABGRENZUNGS-LINIE))

(DEFINE-PRIMITIVE-CONCEPT ABGRENZUNG-FLAECHENHAFTER-GEWAESSER-UNSICHTBAR-LINIE* (AND ABGRENZUNGS-LINIE))

(DEFINE-PRIMITIVE-CONCEPT FLAECHENH-GEWAESSERBEGR-LINIE* (AND ABGRENZUNGS-LINIE))

(DEFINE-PRIMITIVE-CONCEPT FLAECHENH-GEWAESSERBEGR-SCHIFFBAR-LINIE* (AND FLAECHENH-GEWAESSERBEGR-LINIE*))

(DEFINE-PRIMITIVE-CONCEPT FLAECHENH-GEWAESSERBEGR-NICHT-SCHIFFBAR-LINIE* (AND FLAECHENH-GEWAESSERBEGR-LINIE*))

(DEFINE-PRIMITIVE-CONCEPT KONTUR-FUER-OEFFENTLICHES-GEBAEUDE-LINIE* (AND KONTUR-LINIE))

;;;
;;; Symbole
;;;

(DEFINE-PRIMITIVE-CONCEPT FLIESSRICHTUNGSPFEIL-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL))

(DEFINE-PRIMITIVE-CONCEPT MOOR-SUMPF-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL))

(DEFINE-PRIMITIVE-CONCEPT WIESE-WEIDE-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL))

(DEFINE-PRIMITIVE-CONCEPT KILOMETRIERUNG-BAB-BAB-AEHNLICH-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL))

(DEFINE-PRIMITIVE-CONCEPT FRIEDHOF-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL))

(DEFINE-PRIMITIVE-CONCEPT FRIEDHOF-FUER-NICHTCHRISTEN-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL))

(DEFINE-PRIMITIVE-CONCEPT P+R-SYMBOL-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL))

(DEFINE-PRIMITIVE-CONCEPT P+R-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL))

(DEFINE-PRIMITIVE-CONCEPT U-BAHN-STATION-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL U-BAHN-STATION))

(DEFINE-PRIMITIVE-CONCEPT S-BAHN-STATION-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL S-BAHN-STATION))

(DEFINE-PRIMITIVE-CONCEPT KLEINGARTEN-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL KLEINGARTEN))

(DEFINE-PRIMITIVE-CONCEPT POSTAMT-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL POSTAMT)) 

(DEFINE-PRIMITIVE-CONCEPT KIRCHE-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL KIRCHE))

(DEFINE-PRIMITIVE-CONCEPT KAPELLE-SYMBOL* (AND KARTOGRAFISCHES-SYMBOL KAPELLE))

(DEFINE-PRIMITIVE-CONCEPT NADELBAUM-SYMBOL* (AND KARTOGRAFISCHES-OBJEKT NADELBAUM))

(DEFINE-PRIMITIVE-CONCEPT NADELHOLZ-SYMBOL* (AND KARTOGRAFISCHES-OBJEKT NADELBAUM))

(DEFINE-PRIMITIVE-CONCEPT LAUBBAUM-SYMBOL* (AND KARTOGRAFISCHES-OBJEKT LAUBBAUM))

(DEFINE-PRIMITIVE-CONCEPT LAUBHOLZ-SYMBOL* (AND KARTOGRAFISCHES-OBJEKT LAUBBAUM))


;;;
;;; Natuerliche Objekte und Artefakte 
;;;

(DEFINE-PRIMITIVE-CONCEPT NATUERLICHES-OBJEKT (AND GEO-OBJEKT))

(DEFINE-PRIMITIVE-CONCEPT VEGETATIVES-OBJEKT (AND NATUERLICHES-OBJEKT)) ; "lebt"

(DEFINE-PRIMITIVE-CONCEPT ARTEFAKT (AND GEO-OBJEKT))

;;;
;;; Spezielle Artefakte 
;;;

(DEFINE-PRIMITIVE-CONCEPT EINRICHTUNG (AND ARTEFAKT))

(DEFINE-PRIMITIVE-CONCEPT TECHNISCHE-EINRICHTUNG (AND EINRICHTUNG))

(DEFINE-PRIMITIVE-CONCEPT INSTITUTION (AND ARTEFAKT))

(DEFINE-PRIMITIVE-CONCEPT INFRASTRUKTUR (AND EINRICHTUNG))

;;;
;;; Gebaeude 
;;;

(DEFINE-PRIMITIVE-CONCEPT GEBAEUDE (AND ARTEFAKT ))

(DEFINE-PRIMITIVE-CONCEPT OEFFENTLICHES-GEBAEUDE (AND GEBAEUDE FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT OEFFENTLICHES-GEBAEUDE-FLAECHE* (AND OEFFENTLICHES-GEBAEUDE))

(DEFINE-PRIMITIVE-CONCEPT NUTZGEBAEUDE (AND GEBAEUDE))

(DEFINE-PRIMITIVE-CONCEPT WOHNGEBAEUDE (AND GEBAEUDE))

(DEFINE-PRIMITIVE-CONCEPT POSTAMT (AND SYMBOL OEFFENTLICHES-GEBAEUDE INSTITUTION NUTZGEBAEUDE))

(DEFINE-PRIMITIVE-CONCEPT KIRCHE (AND SYMBOL OEFFENTLICHES-GEBAEUDE INSTITUTION NUTZGEBAEUDE))

(DEFINE-PRIMITIVE-CONCEPT KAPELLE (AND SYMBOL KIRCHE))

(DEFINE-PRIMITIVE-CONCEPT KLEINGARTEN (AND SYMBOL WOHNGEBAEUDE))

(DEFINE-PRIMITIVE-CONCEPT WOHNHAUS (AND WOHNGEBAEUDE))

(DEFINE-PRIMITIVE-CONCEPT EINFAMILIENHAUS (AND WOHNHAUS))

(DEFINE-PRIMITIVE-CONCEPT MEHRFAMILIENHAUS (AND WOHNHAUS))

(DEFINE-PRIMITIVE-CONCEPT MIETSHAUS (AND WOHNHAUS))

(DEFINE-PRIMITIVE-CONCEPT BEHOERDE (AND GEBAEUDE INSTITUTION NUTZGEBAEUDE OEFFENTLICHES-GEBAEUDE))

(DEFINE-PRIMITIVE-CONCEPT SCHULE (AND BEHOERDE))

(DEFINE-PRIMITIVE-CONCEPT U-BAHN-STATION (AND INFRASTRUKTUR TECHNISCHE-EINRICHTUNG OEFFENTLICHES-GEBAEUDE))

(DEFINE-PRIMITIVE-CONCEPT S-BAHN-STATION (AND INFRASTRUKTUR TECHNISCHE-EINRICHTUNG OEFFENTLICHES-GEBAEUDE))


;;;
;;; Natuerliche Flaechen
;;;

(DEFINE-PRIMITIVE-CONCEPT NATUERLICHE-FLAECHE (AND NATUERLICHES-OBJEKT FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT VEGETATIVE-FLAECHE (AND NATUERLICHE-FLAECHE VEGETATIVES-OBJEKT)) 

(DEFINE-PRIMITIVE-CONCEPT KULTIVIERTE-FLAECHE (AND NATUERLICHE-FLAECHE ARTEFAKT))

;;;
;;; 
;;;

(DEFINE-PRIMITIVE-CONCEPT LANDWIRTSCHAFTLICHE-FLAECHE (AND KULTIVIERTE-FLAECHE VEGETATIVE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT GRUENFLAECHE (AND VEGETATIVE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT RASENFLAECHE (AND GRUENFLAECHE KULTIVIERTE-FLAECHE ARTEFAKT))

(DEFINE-PRIMITIVE-CONCEPT BRACHFLAECHE (AND NATUERLICHE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT BRACHFLAECHE-FLAECHE* (AND BRACHFLAECHE))

(DEFINE-PRIMITIVE-CONCEPT GEHOELZ (AND GRUENFLAECHE BRACHFLAECHE-FLAECHE*))

(DEFINE-PRIMITIVE-CONCEPT GEHOELZ-FLAECHE* (AND GEHOELZ))

(DEFINE-PRIMITIVE-CONCEPT WIESE-WEIDE (AND GRUENFLAECHE))

(DEFINE-PRIMITIVE-CONCEPT WIESE-WEIDE-FLAECHE* (AND WIESE-WEIDE))

;;;
;;; Nicht-natuerliche Flaechen sind "prepariert"
;;;

(DEFINE-PRIMITIVE-CONCEPT PREPARIERTE-FLAECHE (AND ARTEFAKT FLAECHE))

;;;
;;; Verschiedene spezielle preparierte Flaechen 
;;;

(DEFINE-PRIMITIVE-CONCEPT PARKARTIGE-FLAECHE (AND PREPARIERTE-FLAECHE RASENFLAECHE))

(DEFINE-PRIMITIVE-CONCEPT BEBAUTE-FLAECHE (AND PREPARIERTE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT ASPHALTIERTE-FLAECHE (AND BEBAUTE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT PLATZ-FLAECHE (AND PREPARIERTE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT BETRIEBSGELAENDE (AND BEBAUTE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT FUSSGAENGERZONE (AND ASPHALTIERTE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT FUSSGAENGERZONE-FLAECHE* (AND FUSSGAENGERZONE))

(DEFINE-PRIMITIVE-CONCEPT PARKPLATZ (AND PLATZ-FLAECHE ASPHALTIERTE-FLAECHE INFRASTRUKTUR))

(DEFINE-PRIMITIVE-CONCEPT PARKPLATZ-FLAECHE* (AND PARKPLATZ))

(DEFINE-PRIMITIVE-CONCEPT FRIEDHOF (AND PARKARTIGE-FLAECHE EINRICHTUNG INSTITUTION))

(DEFINE-PRIMITIVE-CONCEPT FRIEDHOF-FLAECHE* (AND FRIEDHOF))

(DEFINE-PRIMITIVE-CONCEPT FRIEDHOF-FUER-NICHTCHRISTEN-FLAECHE* (AND FRIEDHOF-FLAECHE*))

(DEFINE-PRIMITIVE-CONCEPT SPORTPLATZ (AND RASENFLAECHE PLATZ-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT SPORTPLATZINNENFLAECHE-FLAECHE* (AND SPORTPLATZ))

(DEFINE-PRIMITIVE-CONCEPT PARK (AND PARKARTIGE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT PARK-MIT-EINZELSYMBOLEN-FLAECHE* (AND PARK))

(DEFINE-PRIMITIVE-CONCEPT MARKTPLATZ (AND PLATZ-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT RASTPLATZ (AND PLATZ-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT FESTPLATZ (AND PLATZ-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT PLATZ-Z-B-MARKTPLATZ-RASTPLATZ-FESTPLATZ-FLAECHE* (AND MARKTPLATZ RASTPLATZ FESTPLATZ))

(DEFINE-PRIMITIVE-CONCEPT BAHNBETRIEBSGELAENDE (AND BETRIEBSGELAENDE TECHNISCHE-EINRICHTUNG INFRASTRUKTUR))

(DEFINE-PRIMITIVE-CONCEPT BAHNBETRIEBSGELAENDE-FLAECHE* (AND BAHNBETRIEBSGELAENDE))

(DEFINE-PRIMITIVE-CONCEPT INDUSTRIE (AND BETRIEBSGELAENDE TECHNISCHE-EINRICHTUNG))

(DEFINE-PRIMITIVE-CONCEPT GEWERBE (AND BETRIEBSGELAENDE))

(DEFINE-PRIMITIVE-CONCEPT INDUSTRIE-GEWERBE (AND INDUSTRIE GEWERBE))

(DEFINE-PRIMITIVE-CONCEPT INDUSTRIE-GEWERBE-FLAECHE* (AND INDUSTRIE-GEWERBE))

(DEFINE-PRIMITIVE-CONCEPT WOHNGEBIET (AND BEBAUTE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT WOHNEN (AND BEBAUTE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT WOHNEN-FLAECHE* (AND WOHNGEBIET WOHNEN))

(DEFINE-PRIMITIVE-CONCEPT KLEINGARTENVEREIN (AND BEBAUTE-FLAECHE GRUENFLAECHE))

(DEFINE-PRIMITIVE-CONCEPT SCHREBERGARTENVEREIN (AND BEBAUTE-FLAECHE GRUENFLAECHE))

(DEFINE-PRIMITIVE-CONCEPT KLEINGARTEN-FLAECHE* (AND KLEINGARTENVEREIN SCHREBERGARTENVEREIN))

;;; 
;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT WASSER (AND NATUERLICHES-OBJEKT))

(DEFINE-PRIMITIVE-CONCEPT SCHIFFBARES-WASSER (AND WASSER))

(DEFINE-PRIMITIVE-CONCEPT NICHT-SCHIFFBARES-WASSER (AND WASSER))

;;;
;;; Verschiedene natuerliche Flaechen
;;;

(DEFINE-PRIMITIVE-CONCEPT WASSERFLAECHE (AND WASSER NATUERLICHE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT TEICH (AND WASSERFLAECHE))

(DEFINE-PRIMITIVE-CONCEPT SEE (AND WASSERFLAECHE))

(DEFINE-PRIMITIVE-CONCEPT FLUSS (AND WASSERFLAECHE))

(DEFINE-PRIMITIVE-CONCEPT KANAL (AND WASSERFLAECHE))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT TEICH-NICHT-SCHIFFBAR (AND TEICH NICHT-SCHIFFBARES-WASSER))

(DEFINE-PRIMITIVE-CONCEPT TEICH-NICHT-SCHIFFBAR-FLAECHE* (AND TEICH-NICHT-SCHIFFBAR))


(DEFINE-PRIMITIVE-CONCEPT SEE-NICHT-SCHIFFBAR (AND SEE NICHT-SCHIFFBARES-WASSER))

(DEFINE-PRIMITIVE-CONCEPT SEE-NICHT-SCHIFFBAR-FLAECHE* (AND SEE-NICHT-SCHIFFBAR))


(DEFINE-PRIMITIVE-CONCEPT SEE-SCHIFFBAR (AND SEE SCHIFFBARES-WASSER))

(DEFINE-PRIMITIVE-CONCEPT SEE-SCHIFFBAR-FLAECHE* (AND SEE-SCHIFFBAR))


(DEFINE-PRIMITIVE-CONCEPT FLUSS-SCHIFFBAR (AND FLUSS SCHIFFBARES-WASSER))

(DEFINE-PRIMITIVE-CONCEPT FLUSS-SCHIFFBAR-FLAECHE* (AND FLUSS-SCHIFFBAR))


(DEFINE-PRIMITIVE-CONCEPT FLUSS-NICHT-SCHIFFBAR (AND FLUSS NICHT-SCHIFFBARES-WASSER))

(DEFINE-PRIMITIVE-CONCEPT FLUSS-NICHT-SCHIFFBAR-FLAECHE* (AND FLUSS-NICHT-SCHIFFBAR))



(DEFINE-PRIMITIVE-CONCEPT KANAL-SCHIFFBAR (AND KANAL SCHIFFBARES-WASSER))

(DEFINE-PRIMITIVE-CONCEPT KANAL-SCHIFFBAR-FLAECHE* (AND KANAL-SCHIFFBAR))



(DEFINE-PRIMITIVE-CONCEPT KANAL-NICHT-SCHIFFBAR (AND KANAL NICHT-SCHIFFBARES-WASSER))

(DEFINE-PRIMITIVE-CONCEPT KANAL-NICHT-SCHIFFBAR-FLAECHE* (AND KANAL-NICHT-SCHIFFBAR))

;;;
;;; Natuerliche lineare Objekte 
;;;

(DEFINE-PRIMITIVE-CONCEPT NATUERLICHE-LINIE (AND NATUERLICHES-OBJEKT LINIE))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT WASSERLINIE (AND WASSER NATUERLICHE-LINIE))

(DEFINE-PRIMITIVE-CONCEPT BACH (AND WASSERLINIE))

(DEFINE-PRIMITIVE-CONCEPT LINIENH-BACH (AND BACH))

(DEFINE-PRIMITIVE-CONCEPT LINIENH-GRABEN-ODER-KANAL (AND WASSERLINIE))

;;;
;;;
;;;


(DEFINE-PRIMITIVE-CONCEPT LINIENH-KANAL-GRABEN-SCHIFFBAR (AND LINIENH-GRABEN-ODER-KANAL SCHIFFBARES-WASSER))

(DEFINE-PRIMITIVE-CONCEPT LINIENH-KANAL-GRABEN-SCHIFFBAR-LINIE* (AND LINIENH-KANAL-GRABEN-SCHIFFBAR))



(DEFINE-PRIMITIVE-CONCEPT LINIENH-KANAL-GRABEN-NICHT-SCHIFFBAR (AND LINIENH-GRABEN-ODER-KANAL NICHT-SCHIFFBARES-WASSER))

(DEFINE-PRIMITIVE-CONCEPT LINIENH-KANAL-GRABEN-NICHT-SCHIFFBAR-LINIE* (AND LINIENH-KANAL-GRABEN-NICHT-SCHIFFBAR))



(DEFINE-PRIMITIVE-CONCEPT LINIENH-BACH-NICHT-SCHIFFBAR (AND LINIENH-BACH NICHT-SCHIFFBARES-WASSER))

(DEFINE-PRIMITIVE-CONCEPT LINIENH-BACH-NICHT-SCHIFFBAR-LINIE* (AND LINIENH-BACH-NICHT-SCHIFFBAR))

;;;
;;; Verschiedene "vegetative Objekte" 
;;;

(DEFINE-PRIMITIVE-CONCEPT BAUM (AND PUNKT VEGETATIVES-OBJEKT))

(DEFINE-PRIMITIVE-CONCEPT NADELBAUM (AND BAUM))

(DEFINE-PRIMITIVE-CONCEPT LAUBBAUM (AND BAUM))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT WALD (AND GRUENFLAECHE))

(DEFINE-PRIMITIVE-CONCEPT LAUBWALD (AND WALD))

(DEFINE-PRIMITIVE-CONCEPT LAUBWALD-FLAECHE* (AND LAUBWALD))

(DEFINE-PRIMITIVE-CONCEPT NADELWALD (AND WALD))

(DEFINE-PRIMITIVE-CONCEPT NADELWALD-FLAECHE* (AND NADELWALD))

(DEFINE-PRIMITIVE-CONCEPT MISCHWALD (AND LAUBWALD NADELWALD))

(DEFINE-PRIMITIVE-CONCEPT MISCHWALD-FLAECHE* (AND MISCHWALD))

;;;
;;; Landwirtschaftliche Flaechen
;;;

(DEFINE-PRIMITIVE-CONCEPT OBSTANBAUGEBIET (AND LANDWIRTSCHAFTLICHE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT OBSTANBAU-FLAECHE* (AND OBSTANBAUGEBIET))

(DEFINE-PRIMITIVE-CONCEPT ACKER (AND LANDWIRTSCHAFTLICHE-FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT ACKER-FLAECHE* (AND ACKER))

;;;
;;; Verkehrswege (Strassen etc.) 
;;;

(DEFINE-PRIMITIVE-CONCEPT VERKEHRSWEG (AND INFRASTRUKTUR))

(DEFINE-PRIMITIVE-CONCEPT UEBERIRDISCHER-VERKEHRSWEG (AND VERKEHRSWEG))

(DEFINE-PRIMITIVE-CONCEPT UNTERIRDISCHER-VERKEHRSWEG (AND VERKEHRSWEG))

(DEFINE-PRIMITIVE-CONCEPT LKW-ODER-PKW-VERKEHRSWEG (AND VERKEHRSWEG))

(DEFINE-PRIMITIVE-CONCEPT BAHN-VERKEHRSWEG (AND VERKEHRSWEG TECHNISCHE-EINRICHTUNG LINIE))

(DEFINE-PRIMITIVE-CONCEPT U-BAHN-VERKEHRSWEG (AND BAHN-VERKEHRSWEG))

(DEFINE-PRIMITIVE-CONCEPT S-BAHN-VERKEHRSWEG (AND BAHN-VERKEHRSWEG))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT STRASSE-ODER-WEG (AND UEBERIRDISCHER-VERKEHRSWEG))

(DEFINE-PRIMITIVE-CONCEPT STRASSE (AND STRASSE-ODER-WEG ASPHALTIERTE-FLAECHE LKW-ODER-PKW-VERKEHRSWEG))

(DEFINE-PRIMITIVE-CONCEPT WEG (AND STRASSE-ODER-WEG))

(DEFINE-PRIMITIVE-CONCEPT AUTOBAHN (AND STRASSE))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT BAB-FLAECHE* (AND AUTOBAHN FLAECHE))

(DEFINE-PRIMITIVE-CONCEPT AUFFAHRT-AUF-BAB-BAB-AEHNLICH-B-LINIE* (AND AUTOBAHN STRASSE LINIE))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT BUNDESSTRASSE (AND STRASSE))

(DEFINE-PRIMITIVE-CONCEPT BUNDESSTRASSE-FLAECHE* (AND FLAECHE BUNDESSTRASSE))

(DEFINE-PRIMITIVE-CONCEPT BUNDESSTRASSE-LINIE* (AND LINIE BUNDESSTRASSE))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT SONSTIGE-STRASSE (AND STRASSE LINIE))

(DEFINE-PRIMITIVE-CONCEPT SONSTIGE-STRASSE-LINIE* (AND SONSTIGE-STRASSE))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT HAUPTVERKEHRSSTRASSE (AND STRASSE LINIE))

(DEFINE-PRIMITIVE-CONCEPT HAUPTVERKEHRSSTRASSE-LINIE* (AND HAUPTVERKEHRSSTRASSE))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT U-BAHN-UNTERIRDISCH (AND U-BAHN-VERKEHRSWEG UNTERIRDISCHER-VERKEHRSWEG))

(DEFINE-PRIMITIVE-CONCEPT U-BAHN-UNTERIRDISCH-LINIE* (AND U-BAHN-UNTERIRDISCH))

(DEFINE-PRIMITIVE-CONCEPT U-BAHN-OBERIRDISCH (AND U-BAHN-VERKEHRSWEG UEBERIRDISCHER-VERKEHRSWEG))

(DEFINE-PRIMITIVE-CONCEPT U-BAHN-OBERIRDISCH-LINIE* (AND U-BAHN-OBERIRDISCH))

(DEFINE-PRIMITIVE-CONCEPT S-BAHN-UNTERIRDISCH (AND S-BAHN-VERKEHRSWEG UNTERIRDISCHER-VERKEHRSWEG))

(DEFINE-PRIMITIVE-CONCEPT S-BAHN-UNTERIRDISCH-LINIE* (AND S-BAHN-UNTERIRDISCH))

(DEFINE-PRIMITIVE-CONCEPT S-BAHN-OBERIRDISCH (AND S-BAHN-VERKEHRSWEG UEBERIRDISCHER-VERKEHRSWEG))

(DEFINE-PRIMITIVE-CONCEPT S-BAHN-OBERIRDISCH-LINIE* (AND S-BAHN-OBERIRDISCH))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT VERKEHRSBEGLEITGRUEN (AND INFRASTRUKTUR GRUENFLAECHE))

(DEFINE-PRIMITIVE-CONCEPT VERKEHRSBEGLEITGRUEN-FLAECHE* (AND VERKEHRSBEGLEITGRUEN))

;;;
;;;
;;;

(DEFINE-PRIMITIVE-CONCEPT WEG-HINTEGRUND-IN-FLAECHENFARBE-LINIE* (AND WEG LINIE))

(DEFINE-PRIMITIVE-CONCEPT BRUECKE (AND VERKEHRSWEG UEBERIRDISCHER-VERKEHRSWEG LINIE))

(DEFINE-PRIMITIVE-CONCEPT BRUECKE-LINIE* (AND BRUECKE))

(DEFINE-PRIMITIVE-CONCEPT BAHNANLAGE (AND INFRASTRUKTUR TECHNISCHE-EINRICHTUNG LINIE))

(DEFINE-PRIMITIVE-CONCEPT NEBENBAHN-HAFENB-RANGIERANL-USW-OBERIRDISCH-LINIE* (AND BAHNANLAGE))

